version: 2.1

parameters:
  GHA_Actor:
    type: string
    default: "ps1312"
  GHA_Action:
    type: string
    default: "CI_iOS"
  GHA_Event:
    type: string
    default: "pull_request"
  GHA_Meta:
    type: string
    default: ""

jobs:
  build-and-test:
    macos:
      xcode: 14.1

    steps:
      - checkout
      - run: xcodebuild clean build test -project TriviaEngine/TriviaEngine.xcodeproj -scheme "TriviaEngine" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
      - run: xcodebuild clean build test -workspace TriviaApp.xcworkspace -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=16.1,name=iPhone 14" ONLY_ACTIVE_ARCH=YES

workflows:
  continuous-integration:
    when: << pipeline.parameters.GHA_Action >>
    jobs:
      - build-and-test